In [2]:
import numpy as np

In [3]:
# Criando a GRID por meio de um ARRAY MULTIDIMENSIONAL com NumPy
x_dimension = 3
y_dimension = 6
robot = 1

In [4]:
grid = np.zeros((x_dimension, y_dimension))

In [5]:
grid

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
# Colocando o Robo para iniciar no canto inferior esquerdo da Grade
grid[grid.shape[0] - 1][0] = robot

# Caso queira que seja do canto inferior direito da Grade
# grid[grid.shape[0] - 1][grid.shape[1] - 1] = robot

In [7]:
grid

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [16]:
def move(direction, x, y):
    if x > grid.shape[0] - 1 and y > grid.shape[1] - 1:
        if direction == 'up':
            grid[x][y] = 0
            grid[x - 1][y] = robot
        if direction == 'down':
            grid[x][y] = 0
            grid[x + 1][y] = robot
        if direction == 'left':
            grid[x][y] = 0
            grid[x][y - 1] = robot
        if direction == 'right':
            grid[x][y] = 0
            grid[x][y + 1] = robot
    else:
        print('Out of Grid limit!')

In [19]:
move('right', grid.shape[0] - 1, 0)

Out of Grid limit!


In [20]:
grid

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [21]:
move('down', grid.shape[0] - 1, 0)

Out of Grid limit!
